/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

/**
 *
 * @author Alunos
 */
public class Esporte_coletivo extends javax.swing.JFrame {

    /**
     * Creates new form Consultorio
     */
    public Esporte_coletivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jAreaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmJanela1 = new javax.swing.JMenu();
        jmMedico = new javax.swing.JMenuItem();
        jmConsultarMedico = new javax.swing.JMenuItem();
        jmJanela2 = new javax.swing.JMenu();
        jmCadastrarPaciente = new javax.swing.JMenuItem();
        jmConsultaPaciente = new javax.swing.JMenuItem();
        jmJanela3 = new javax.swing.JMenu();
        jmCadastrarConsulta = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jAreaTrabalhoLayout = new javax.swing.GroupLayout(jAreaTrabalho);
        jAreaTrabalho.setLayout(jAreaTrabalhoLayout);
        jAreaTrabalhoLayout.setHorizontalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        jAreaTrabalhoLayout.setVerticalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        jmJanela1.setText("Jogador");

        jmMedico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jmMedico.setText("Cadastrar jogador");
        jmMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMedicoActionPerformed(evt);
            }
        });
        jmJanela1.add(jmMedico);

        jmConsultarMedico.setText("Consultar Jogador");
        jmConsultarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultarMedicoActionPerformed(evt);
            }
        });
        jmJanela1.add(jmConsultarMedico);

        jMenuBar1.add(jmJanela1);

        jmJanela2.setText("Time");

        jmCadastrarPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jmCadastrarPaciente.setText("Cadastrar Time");
        jmCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastrarPacienteActionPerformed(evt);
            }
        });
        jmJanela2.add(jmCadastrarPaciente);

        jmConsultaPaciente.setText("Consultar");
        jmConsultaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaPacienteActionPerformed(evt);
            }
        });
        jmJanela2.add(jmConsultaPaciente);

        jMenuBar1.add(jmJanela2);

        jmJanela3.setText("Consultar Jogos");

        jmCadastrarConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jmCadastrarConsulta.setText("Consultar Jogos");
        jmCadastrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastrarConsultaActionPerformed(evt);
            }
        });
        jmJanela3.add(jmCadastrarConsulta);

        jMenuBar1.add(jmJanela3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void CadastroJogador(){
        CadastraJogador gcp = new CadastraJogador();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
    private void jmMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMedicoActionPerformed
    CadastroJogador();
    }//GEN-LAST:event_jmMedicoActionPerformed
    private void abrirConsultaJogador(){
        ConsultaJogador gcp = new ConsultaJogador();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
    private void jmConsultarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultarMedicoActionPerformed
        abrirConsultaJogador();// TODO add your handling code here:
    }//GEN-LAST:event_jmConsultarMedicoActionPerformed
private void abrirCadastroTime(){
        CadastrarTime gcp = new CadastrarTime();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
    private void jmCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastrarPacienteActionPerformed
        abrirCadastroTime();// TODO add your handling code here:
    }//GEN-LAST:event_jmCadastrarPacienteActionPerformed
private void abrirConsultaTime(){
        ConsultaTime gcp = new ConsultaTime();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
    private void jmConsultaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaPacienteActionPerformed
        abrirConsultaTime();// TODO add your handling code here:
    }//GEN-LAST:event_jmConsultaPacienteActionPerformed
private void abrirConsultaJogos(){
        ConsultaJogos gcp = new ConsultaJogos();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
    private void jmCadastrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastrarConsultaActionPerformed
       abrirConsultaJogos();// TODO add your handling code here:
    }//GEN-LAST:event_jmCadastrarConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Esporte_coletivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Esporte_coletivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Esporte_coletivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Esporte_coletivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Esporte_coletivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jmCadastrarConsulta;
    private javax.swing.JMenuItem jmCadastrarPaciente;
    private javax.swing.JMenuItem jmConsultaPaciente;
    private javax.swing.JMenuItem jmConsultarMedico;
    private javax.swing.JMenu jmJanela1;
    private javax.swing.JMenu jmJanela2;
    private javax.swing.JMenu jmJanela3;
    private javax.swing.JMenuItem jmMedico;
    // End of variables declaration//GEN-END:variables
}
